### ISSUE TITLE
NPM module is outdate

### ISSUE THREAD

**Issue by ibbatta** [LazoCoder/Pokemon-Terminal#123]
Actually, if I install the repo with npm, asks me "random" to show a random pokemon in my terminal. I suppose that npm mobule is not updated

**Comment by samosaara** [comment]
Extremely high chance of so, I was the one who made the changes to the command engine yet I wasn't the one to publish it in NPM, I don't even think I have access to update it, according to the readme, @therealklanni was the one responsible and therefore should have the rights to it. I bet a lot of the downloads come from there, and it should be updated

**Comment by ibbatta** [comment]
Don't worry it's just an advice for you.
Actually it works so I'm still happy ahahah (btw is not updated 😆 )

**Comment by sylveon** [comment]
IMO we shouldn't have published it on NPM:

- We need third-parties to update the package, while the package on the AUR for example will always install the latest version.
- People install it not knowing it requires Python (#36), because NPM is for JavaScript libs/programs mostly.
- Since it requires Python, people who actually have it installed can easily use PIP to install it now: `pip install git+https://github.com/LazoCoder/Pokemon-Terminal.git`.
- I'll be honest, I have a general distaste for NPM and Node.

**Comment by LazoCoder** [comment]
I've updated the npm package to the latest version.

I haven't tested the PIP install but if it works we should add it to the readme.

**Comment by therealklanni** [comment]
npm isn't "for JS", JS just happens to be what it's _mostly_ used for. There are plenty of Python, Bash, and other language packages released on npm 😄
