### ISSUE TITLE
"pokemon -c" not working

### ISSUE THREAD

**Issue by LazoCoder** [LazoCoder/Pokemon-Terminal#131]
On my mac, when I do "pokemon -c" it gets stuck and nothing happens. When I ctrl+c out of it I get this error:
```
^CTraceback (most recent call last):
  File "/usr/local/bin/pokemon", line 8, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/node_modules/pokemon-terminal/pokemonterminal/main.py", line 114, in main
    pipe_out = os.open(PIPE_PATH, os.O_WRONLY)
KeyboardInterrupt
```

**Comment by cclauss** [comment]
The exception raised after you hit control-c is the right one https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt

**Comment by sylveon** [comment]
Looks like it's stuck at making the pipe

**Comment by samosaara** [comment]
Oh OK, I was scared that was a Mac OS problem, but no it's on my logic, I've been able to reproduce it here (I think)... so the problem is when you, after using the slideshow for at least once, if try to stop it without starting it again, it gets stuck waiting for the other end. Which will never answer. So the problem is twofold, we need to check if the file exists before trying to open it and we will need to delete the pipe file after we are done.

**Comment by samosaara** [comment]
Did that fix it @LazoCoder? Can we close this one?

**Comment by LazoCoder** [comment]
Yes, its fixed, thanks.
