### ISSUE TITLE
Suggestion: use distutils to allow a system wide install

### ISSUE THREAD

**Issue by sylveon** [LazoCoder/Pokemon-Terminal#16]
This would streamline the creation of an Arch Linux User Repository package after PR #14 is merged

**Comment by samosaara** [comment]
Well and since this is pretty much a python app I think pip would be great too

**Comment by cclauss** [comment]
It certainly would be a helpful to be able to `pip install pokemon_terminal`.  @charlesmilette , @caedus75 would you be interested in [working on this one](https://packaging.python.org/) with me?

**Comment by caedus75** [comment]
@cclauss I'm interested!

I have a `setup.py` I wrote once, will adapt it to work in this project.

**Comment by cclauss** [comment]
Great news...  Two words of warning

1. We will need to establish the notion of [releases](https://github.com/LazoCoder/Pokemon-Terminal/releases) which this project currently does not have.
    * We only push to PyPI after we have a new release.
2. I am a stickler for [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) which show up at the lower left of a project's PyPI page:
    * Good use of trove classifiers: [requests](https://pypi.org/project/requests)
    * Not so good: [mxnet-cu80](https://pypi.org/project/mxnet-cu80)

**Comment by caedus75** [comment]
I managed to get a 'working' [`setup.py`](https://github.com/caedus75/Pokemon-Terminal/blob/pip/setup.py), think of it as a draft. It's installing but could be better, IMO.

To find all python files, specially the ones on the root of the repo, the root itself need to be set as a package. This has a side effect:
```
$ ls venv/lib/python3.6/site-packages
Data         pip-9.0.1.dist-info               setuptools                   main.py           test_main.py
Images       pkg_resources                     setuptools-36.0.1.dist-info  pytest.py         test_scripter.py
__pycache__  pokemon_terminal-0.0.1.dist-info  wheel                        scripter.py       test_utils.py
_pytest      py                                wheel-0.29.0.dist-info       setup.py          unittest.py
adapter      py-1.4.34.dist-info               database.py                  test_broken.py
pip          pytest-3.1.3.dist-info            easy_install.py              test_database.py
```

See how everything is scattered all over site-packages, even the project `setup.py` is installed.

I think would be beneficial to change the folder structure of the repo before continuing - move all code and tests to a `pokemonterminal` folder and leave the repo's root to readme, licence etc - but this needs to be discussed since it may cause breakage to the open PRs.

So, besides establishing the notion of releases, there's this change to the folder structure to think about.

**Comment by charlesmilette** [comment]
I just suggested it, but myself am not really good at Python 🙄

Le ven. 7 juil. 2017 17:22, Carlos Millett <notifications@github.com> a
écrit :
