### ISSUE TITLE
Kitty support

### ISSUE THREAD

**Issue by carlosvigil** [LazoCoder/Pokemon-Terminal#207]
Is it possible to add or build kitty support? How would I go about that?

**Comment by sylveon** [comment]
You would need to add an adapter in https://github.com/LazoCoder/Pokemon-Terminal/tree/master/pokemonterminal/terminal/adapters

**Comment by carlosvigil** [comment]
Kitty uses PNG, meaning I might require image magick or something similar to convert the files. I haven't found an original image source, looks like their servers are down.

**Comment by sylveon** [comment]
No PNG support at all? That's interesting

**Comment by sylveon** [comment]
1-a 2-b sounds like what I'd do as well!

**Comment by cnschn** [comment]
Huh. I just tried, and I can set jpg backgrounds just fine :shrug: Not sure if that's some unspecified behavior that randomly works, because the last comment I saw by the kitty developer on this topic still said that only png was supported. I'll go take a look at the kitty source if I can find a definitive answer, but that would make the kitty integration pretty simple (I have it working right now).

There is one unfortunate thing though - to dynamically set the background for a kitty instance, we need to use the [remote control feature](https://sw.kovidgoyal.net/kitty/remote-control/). This needs to be enabled in the kitty config, but there are a bunch of different ways to go about it (over TTY only, over a socket, with or without password protection (which is probably a good idea to have)). The easiest way to go would be to say "if you want to use Pokemon-Terminal with kitty, you need to fully enable remote control without a password" but I don't think I'd like this approach :smile:

The best thing would probably be to direct the user to setup a specific password for Pokemon-Terminal to use that only grants permissions to set the background, this would look like:

```
remote_control_password "missingno" set-background-image
```

Unfortunately this would need some configuration for Pokemon-Terminal, to tell the kitty adapter which password to use, either using a config file, environment variables or additional parameters... Any thoughts?

**Comment by sylveon** [comment]
Kitty documents that the CLI tool defaults to reading a passwords from the `KITTY_RC_PASSWORD` environment variable - so it seems to me that the easiest way to get is to just get users to set this themselves. Thoughts?

**Comment by cnschn** [comment]
Oh, I like that a lot! Then we can just put a note in the readme that kitty support needs remote control permissions to execute `set-background-image`, and it's up to the user to make that happen. Allowing RC without password would be one (not great) way, setting up a password and passing it in the environment variable another one.

I'll check if this works as expected and whip up a PR!

Silly sidenote: If I were to add a line to the readme about what needs to be put in the kitty config, do you think "missingno" as an example password would be fine, or is "<your-password-here>" a safer choice? I just found it really funny when typing the comment above 😅

**Comment by sylveon** [comment]
Haha yeah missingno works fine as example password

**Comment by cnschn** [comment]
It's bizarre, I'm not familiar with kitty's codebase, but it really does look like it should only support PNG files. Still, #214 just works for me? I opened [a discussion](https://github.com/kovidgoyal/kitty/discussions/7636) in the kitty project, let's wait for some feedback there. In the meantime, I'd be glad if anyone using kitty can give this a try. Maybe @carlosvigil is still interested, a good year later? :smile:
