### ISSUE TITLE
[Request] Hyper Terminal Support

### ISSUE THREAD

**Issue by DuIslingr** [LazoCoder/Pokemon-Terminal#25]
I would love to see this available for Hyper on Windows/Linux/and Mac. It does utilize Electron so idk how difficult it would be to get it to work.

https://github.com/zeit/hyper

**Comment by klauscfhq** [comment]
Hi! Love the project! Started building a hyper version last night! Here it is!

https://github.com/klauscfhq/hyper-pokemon

Here are a few screenshots​!
![Screen](https://cdn.rawgit.com/klauscfhq/hyper-pokemon/e66c2a4c/media/screen.png)

![Screens](https://cdn.rawgit.com/klauscfhq/hyper-pokemon/cb43900d/media/screens.png)

It's still early days, but there will be support for all pokemon backgrounds really fast​!
Go on and give it a try!

**Comment by charlesmilette** [comment]
I wonder if it could be possible to integrate it in this project instead of making it completely separate.

**Comment by klauscfhq** [comment]
I think it would be really hard, since hyper is build solely on web technologies :)
Though you could definitely try, plus building it natively for hyper could open new applications, like support for the atom text editor and other electron apps. 😁

**Comment by DuIslingr** [comment]
@klauscfhq You my friend have earned yourself a star from me :p

**Comment by LazoCoder** [comment]
It wouldn't be hard to do this. Its really just a two step process:

1. Locate Hyper's config file.
2. Inject the following code:
```
module.exports = {
  css: `
    .terms_terms {
      background: url(file://path-to-pokemon-image) center;
      background-size: cover;
    }
  `,

  termCSS: `
    x-screen {
      background: transparent !important;
    }
  `
};
```

**Comment by klauscfhq** [comment]
It is not just that, there are other things also involved, an you should probably know that this way of using background images is not a officially supported one by Electron, which means that it might completely change with a new release. Also there are other things to take into account, such as providing support for other Hyper related features and issues, that would require a more JavaScript oriented codebase instead of Python one. Plus you are cutting down a whole OS platform on the original project, the Windows one, which with hyper is supported. In addition there is a whole ecosystem of already available color-schemes & plugins that could be combined with the Pokemon backgrounds on Hyper and supporting them would definitely​ be a serious extra development weight on the existing project. Again, you can definitely try applying it. Just to be clear, i have not forked your code, i am just using as an inspiration to be build new things, like the Hyper theme, a future Atom theme, Trello themes, Caprine themes etc 😁
