### ISSUE TITLE
Make off an alias of clear

### ISSUE THREAD

**Issue by giftig** [LazoCoder/Pokemon-Terminal#30]
And maybe exit, blank, none? Otherwise you get this rather amusing result instead:

![screen shot 2017-06-13 at 09 35 51](https://user-images.githubusercontent.com/2862039/27074028-b6891900-501d-11e7-9e47-89b7218b03ec.png)

**Comment by LazoCoder** [comment]
I could add in this alias very easily. In fact I had a bunch of different aliases for several commands but I removed them since I wasn't sure if it was bad practice to do this. Also I wasn't sure how to put it in the help section in a way that wouldn't confuse people. I was gonna do:
```
$ pokemon help
    ...
Other Parameters:
    ...
    pokemon clear | off | disable          -   Clear the Pokemon in the terminal.
    ...
```
But what if people don't know what that means. Alternatively I could just do:
```
$ pokemon help
    ...
Other Parameters:
    ...
    pokemon clear           -   Clear the Pokemon in the terminal.
    pokemon off             -   Clear the Pokemon in the terminal.
    pokemon disable         -   Clear the Pokemon in the terminal.
    ...
```
But then it'll be a really long  and repetitive help section.. so I dunno. Any ideas on the best way to do this?
Also, Pokemon Terminal has an internal search system for all inputs of 3 characters or more that do not match any pokemon in the database. So if you type ```pokemon pika``` it will change it to pikachu, if you type ```pokemon dos``` it will change it to gyarados. I should probably add this to the readme so people know about it.

**Comment by LazoCoder** [comment]
I've added the 'off' alias.

**Comment by giftig** [comment]
I think the first way of phrasing it was ok - that syntax should be fairly clear to anyone who is uses a terminal enough to want to pokemon-theme it imo. Alternatively just list it under clear (or whichever one you want to consider to be the "primary" command) and append "`off`, `disable`, and `clear` are all aliases for this command".
