### ISSUE TITLE
pokemon ? is confused by split panes (iterm2)

### ISSUE THREAD

**Issue by giftig** [LazoCoder/Pokemon-Terminal#31]
It will always tell you the last one which you enabled, not the one active in the pane you're in.
![screen shot 2017-06-13 at 09 51 08](https://user-images.githubusercontent.com/2862039/27074084-e922d130-501d-11e7-9c32-91ad50faed78.png)

**Comment by giftig** [comment]
(As a plus note, your poketerminal has made me ~120% happier at work)

**Comment by LazoCoder** [comment]
Yeah the '?' command only checks the most recent pokemon that was set. Its a bit of a "hacky" and unreliable feature since it parses the script the sets background image and each time a new pokemon is set, the script is overwritten.
The only reason I implemented the '?' command is to use it immediately after 'pokemon random' to see what the pokemon is if I do not recognize the image. But it didn't occur to me that people might use the commands in different orders. Also it crashes on terminals that aren't iTerm2.
It was a pretty poor design decision on my part and I'm going to remove this function.

**Comment by giftig** [comment]
If you don't want to do it but you're interested in having that feature work better I'll see if I can put it back in when I get some free time, since I found being able to say "wtf is this pokemon?" pretty useful (and I'm a python dev)

**Comment by LazoCoder** [comment]
If you really want to add the feature, go for it. But I don't think that its worth it as it would add a lot of complexity to the code and it would be a headache to maintain if more terminals become supported. A better, more reliable alternative to ```pokemon ?``` might be to simply print the pokemon name after using ```pokemon random```.
