### ISSUE TITLE
Selecting a theme fails on terminology

### ISSUE THREAD

**Issue by NlightNFotis** [LazoCoder/Pokemon-Terminal#33]
Hello.

I am trying to run the themes in terminology. When I run the command `pokemon random-kanto` I get the following errors on the terminal I have used to spawn terminology:

```
ERR<29944>:terminology media.c:1237 media_add() can not decode '/home/fotis/.Pokemon-Terminal/Images/Generation I - Kanto/139.png'
ERR<29944>:eo lib/eo/eo_ptr_indirection.x:275 _eo_obj_pointer_get() obj_id (nil) is not pointing to a valid object. Maybe it has already been freed.
```

with no obvious change to the theme inside terminology. Am I doing something wrong? I have installed the theme package through the officially described way in the `readme` and I am trying to run it on Terminology on Ubuntu 16.04, with terminology being installed from the distribution repositories.

**Comment by samosaara** [comment]
What is the version of your terminology? That seems to be a terminology error, as in it not being able to decode the image after it has been set, not a fault on our end, It might be also missing dependency but this issue is still relevant because might happen to other ubuntu users. 

Or it also might simply be corrupted download images try cloning the repo again, but that is a far shot git sha-sum's downloads... Why don't you try to download a newer version from terminology or try to compile terminology to source to see if that is a 'too old version' issue

**Comment by charlesmilette** [comment]
Wild guess, but try installing libpng?

De : Samuel Henrique
Envoyé le :13 juin 2017 09:37
À : LazoCoder/Pokemon-Terminal
Cc : Subscribed
Objet :Re: [LazoCoder/Pokemon-Terminal] Selecting a theme fails onterminology (#33)

What is the version of your terminology? That seems to be a terminology error, as in it not being able to decode the image after it has been set, not a fault on our end, It might be also missing dependency but this issue is still relevant because might happen to other ubuntu users.
Or it also might simply be corrupted download images try cloning the repo again, but that is a far shot git sha-sum's downloads... Why don't you try to download a newer version from terminology or try to compile terminology to source to see if that is a 'too old version' issue

**Comment by charlesmilette** [comment]
Can reproduce on Lubuntu, even tried installing `libpng-dev`, didn't change a thing.

**Comment by samosaara** [comment]
Please do try to compile terminology from source or get a .deb of the latest version it might be because the 'stable' version of ubuntu has a old unsolved bug.

**Comment by charlesmilette** [comment]
The terminology edition was effectively too old, you can install a newer one from a PPA (as mentionned [here](https://www.enlightenment.org/distros/ubuntu-start)):

    sudo add-apt-repository ppa:niko2040/e19
    sudo apt-get update
    sudo apt install terminology
